= Community contributions
:toc:
:toc-title:  Overview
:toclevels: 2

This page lists out the amazing contributions our community has made for the Gravitee API Management and Access Management ecosystem. If you'd like your contribution to appear here, please send a pull request to this repostory to add it.

If you're looking to create something amazing for the Gravitee ecosystem and want to bounce ideas around, do reach out to the https://community.gravitee.io[community forum^].

Please note that all listings here are community contributions, and as such are not officially supported by Gravitee.

== Tools

[#tyk-to-gravitee]
=== Tyk to Gravitee API tool

A JavaScript-based tool for https://github.com/mtwomey/gravitee-tool[converting and importing APIs from Tyk to Gravitee^], created by https://github.com/mtwomey[Matthew Twomey^].

[#mcp-crewai]
=== MCP-enabled Gravitee API with CrewAI agent

A demo showing how to connect to an MCP server using Streamable HTTP Transport and use Gravitee MCP tools inside a CrewAI agent to perform real-world tasks like fetching weather data.

*Tags:* `MCP`, `APIM`, `CrewAI`, `AI Agent`, `OpenAPI`
